# Generated by Django 4.2.7 on 2023-11-19 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Phone',
            new_name='phone',
        ),
    ]
