# Generated by Django 4.2.7 on 2023-11-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_rename_phone_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.TextField(default='Effective communication and collaboration are at the core of my professional approach. I thrive in dynamic, fast-paced environments and am adept at adapting to evolving challenges. A natural problem-solver, I am confident in my ability to contribute positively to any team or project.', max_length=1000),
        ),
    ]
