# Generated by Django 4.2.7 on 2023-11-21 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_alter_profile_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.TextField(default='Effective communication and collaboration are at the core of my professional approach. I thrive in dynamic, fast-paced environments and am adept at adapting to evolving challenges. A natural problem-solver, I am confident in my ability to contribute positively to any team or project.'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.profile')),
            ],
        ),
    ]
