# Generated by Django 4.2.7 on 2023-11-21 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_alter_profile_email_alter_profile_summary_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducatioDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=150)),
                ('starting_year', models.DateField()),
                ('end_year', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.profile')),
            ],
        ),
    ]
