# Generated by Django 4.2.7 on 2023-11-21 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0005_educatiodetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EducatioDetail',
            new_name='EducationDetail',
        ),
    ]
